import Provider from "@/Components/Provider";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/Components/Navbar";
import BottomNav from "@/Components/BottomNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <meta name="referrer" content="no-referrer" />
      </head>
      <body className={`${inter.className}`}>
        <Provider>
          <div className="flex w-full">
            <div className="h-screen w-36 sm:block hidden"><Navbar/></div>
            <div className="sm:hidden block"><BottomNav/></div>
            <div className="w-full">{children}</div>
          </div>
          <script
            src="https://kit.fontawesome.com/f8f9825bbd.js"
            crossOrigin="anonymous"
          ></script>
        </Provider>
      </body>
    </html>
  );
}
